### PR TITLE
fix: max line width on tablet up

### LINKED ISSUE #220: Approach line length cap
[](https://mrkr.io/s/628aa7e2416b11207ab7f1f8/0)

Steps to reproduce:

Visit approach on a wide laptop

Actual result:

Line length ends up over what's considered legible (11-12 words).

Expected result:

Cap the max-width so that it fits better, usually around ~600-800px depending on type size. I suspect here 800px works.

---

**Source URL:** [https://companion-studio-eta.vercel.app/approach](https://companion-studio-eta.vercel.app/approach)

**Issue details:** [Open in Marker.io](https://app.marker.io/i/628aa7e2416b11207ab7f1fb_047ad73d30193f2e)

<table><tr><td><strong>Browser</strong></td><td>Chrome 101.0.4951.64</td></tr><tr><td><strong>Screen Size</strong></td><td>1728 x 1117</td></tr><tr><td><strong>OS</strong></td><td>OS X 12.0.1</td></tr><tr><td><strong>Viewport Size</strong></td><td>1728 x 1000</td></tr><tr><td><strong>Zoom Level</strong></td><td>100%</td></tr><tr><td><strong>Pixel Ratio</strong></td><td>@&#8203;2x</td></tr></table>

### PR DESCRIPTION
**Pull request by elenamarinaki**
### Why

Resolves #220 

### What

added max width to the paragraph texts inside the `BlockText` wrappers, so that the line is getting cut shorter

### Checklist

- [ ] Ready to be merged

### CODE REVIEW

**Review by joshuaellis — CHANGES_REQUESTED** [review]
This will break if we use anything but a paragraph node.

**Review by joshuaellis — APPROVED** [review]

**Comment by joshuaellis** [comment]
@mylespalmer i've made the decision to ensure the 50/50 divide remains but cap the text's max width independent of that.

Let me know if this works for you or you'd rather the image scales to avoid white space.

**Comment by mylespalmer** [comment]
Hmmm.. second opinion, @willcompanion — thoughts?

**Comment by willcompanion** [comment]
I think keep it 50/50 IMO

**Comment by mylespalmer** [comment]
OK, approved

**Pull request merged**
